version: "3.9"

services:
  web:
    container_name: web
    image: node
    restart: always
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo/notesdb
      - PORT=8080
      - NODE_ENV=development
    command: /bin/sh -c 'npm install && npm run dev'
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none